package com.eshan.multithreading;

class AngleBrackets {
    synchronized static public void generate(int threadNo){
        for(int i = 1 ; i <= 10 ; i++){
            if(i < 6){
                System.out.print('<');
            } else {
                System.out.print('>');
            }
        }
        System.out.println("Generated By thread"+threadNo);
    }
}
public class StaticSynchronization {
    public static void main(String[] args) {
//        AngleBrackets brackets = new AngleBrackets();
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 1 ; i <= 5 ; i++){
                    AngleBrackets.generate(1);
                }
            }
        }).start();

        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 1 ; i <= 5 ; i++){
                    AngleBrackets.generate(2);
                }
            }
        }).start();
    }
}
